#pragma once

#include "nlohmann/json.hpp"

enum class FactionTraitSymbol {
  kBureaucratic,
  kSecretive,
  kCapitalistic,
  kIndustrious,
  kPeaceful,
  kDistrustful,
  kWelcoming,
  kSmugglers,
  kScavengers,
  kRebellious,
  kExiles,
  kPirates,
  kRaiders,
  kClan,
  kGuild,
  kDominion,
  kFringe,
  kForsaken,
  kIsolated,
  kLocalized,
  kEstablished,
  kNotable,
  kDominant,
  kInescapable,
  kInnovative,
  kBold,
  kVisionary,
  kCurious,
  kDaring,
  kExploratory,
  kResourceful,
  kFlexible,
  kCooperative,
  kUnited,
  kStrategic,
  kIntelligent,
  kResearchFocused,
  kCollaborative,
  kProgressive,
  kMilitaristic,
  kTechnologicallyAdvanced,
  kAggressive,
  kImperialistic,
  kTreasureHunters,
  kDexterous,
  kUnpredictable,
  kBrutal,
  kFleeting,
  kAdaptable,
  kSelfSufficient,
  kDefensive,
  kProud,
  kDiverse,
  kIndependent,
  kSelfInterested,
  kFragmented,
  kCommercial,
  kFreeMarkets,
  kEntrepreneurial,
};
NLOHMANN_JSON_SERIALIZE_ENUM(
    FactionTraitSymbol,
    {
        {FactionTraitSymbol::kBureaucratic, "BUREAUCRATIC"},
        {FactionTraitSymbol::kSecretive, "SECRETIVE"},
        {FactionTraitSymbol::kCapitalistic, "CAPITALISTIC"},
        {FactionTraitSymbol::kIndustrious, "INDUSTRIOUS"},
        {FactionTraitSymbol::kPeaceful, "PEACEFUL"},
        {FactionTraitSymbol::kDistrustful, "DISTRUSTFUL"},
        {FactionTraitSymbol::kWelcoming, "WELCOMING"},
        {FactionTraitSymbol::kSmugglers, "SMUGGLERS"},
        {FactionTraitSymbol::kScavengers, "SCAVENGERS"},
        {FactionTraitSymbol::kRebellious, "REBELLIOUS"},
        {FactionTraitSymbol::kExiles, "EXILES"},
        {FactionTraitSymbol::kPirates, "PIRATES"},
        {FactionTraitSymbol::kRaiders, "RAIDERS"},
        {FactionTraitSymbol::kClan, "CLAN"},
        {FactionTraitSymbol::kGuild, "GUILD"},
        {FactionTraitSymbol::kDominion, "DOMINION"},
        {FactionTraitSymbol::kFringe, "FRINGE"},
        {FactionTraitSymbol::kForsaken, "FORSAKEN"},
        {FactionTraitSymbol::kIsolated, "ISOLATED"},
        {FactionTraitSymbol::kLocalized, "LOCALIZED"},
        {FactionTraitSymbol::kEstablished, "ESTABLISHED"},
        {FactionTraitSymbol::kNotable, "NOTABLE"},
        {FactionTraitSymbol::kDominant, "DOMINANT"},
        {FactionTraitSymbol::kInescapable, "INESCAPABLE"},
        {FactionTraitSymbol::kInnovative, "INNOVATIVE"},
        {FactionTraitSymbol::kBold, "BOLD"},
        {FactionTraitSymbol::kVisionary, "VISIONARY"},
        {FactionTraitSymbol::kCurious, "CURIOUS"},
        {FactionTraitSymbol::kDaring, "DARING"},
        {FactionTraitSymbol::kExploratory, "EXPLORATORY"},
        {FactionTraitSymbol::kResourceful, "RESOURCEFUL"},
        {FactionTraitSymbol::kFlexible, "FLEXIBLE"},
        {FactionTraitSymbol::kCooperative, "COOPERATIVE"},
        {FactionTraitSymbol::kUnited, "UNITED"},
        {FactionTraitSymbol::kStrategic, "STRATEGIC"},
        {FactionTraitSymbol::kIntelligent, "INTELLIGENT"},
        {FactionTraitSymbol::kResearchFocused, "RESEARCH_FOCUSED"},
        {FactionTraitSymbol::kCollaborative, "COLLABORATIVE"},
        {FactionTraitSymbol::kProgressive, "PROGRESSIVE"},
        {FactionTraitSymbol::kMilitaristic, "MILITARISTIC"},
        {FactionTraitSymbol::kTechnologicallyAdvanced,
         "TECHNOLOGICALLY_ADVANCED"},
        {FactionTraitSymbol::kAggressive, "AGGRESSIVE"},
        {FactionTraitSymbol::kImperialistic, "IMPERIALISTIC"},
        {FactionTraitSymbol::kTreasureHunters, "TREASURE_HUNTERS"},
        {FactionTraitSymbol::kDexterous, "DEXTEROUS"},
        {FactionTraitSymbol::kUnpredictable, "UNPREDICTABLE"},
        {FactionTraitSymbol::kBrutal, "BRUTAL"},
        {FactionTraitSymbol::kFleeting, "FLEETING"},
        {FactionTraitSymbol::kAdaptable, "ADAPTABLE"},
        {FactionTraitSymbol::kSelfSufficient, "SELF_SUFFICIENT"},
        {FactionTraitSymbol::kDefensive, "DEFENSIVE"},
        {FactionTraitSymbol::kProud, "PROUD"},
        {FactionTraitSymbol::kDiverse, "DIVERSE"},
        {FactionTraitSymbol::kIndependent, "INDEPENDENT"},
        {FactionTraitSymbol::kSelfInterested, "SELF_INTERESTED"},
        {FactionTraitSymbol::kFragmented, "FRAGMENTED"},
        {FactionTraitSymbol::kCommercial, "COMMERCIAL"},
        {FactionTraitSymbol::kFreeMarkets, "FREE_MARKETS"},
        {FactionTraitSymbol::kEntrepreneurial, "ENTREPRENEURIAL"},
    })

struct FactionTrait {
 public:
  NLOHMANN_DEFINE_TYPE_INTRUSIVE(FactionTrait, symbol, name, description)

 public:
  bool operator==(const FactionTrait&) const = default;

 public:
  FactionTraitSymbol symbol{};
  std::string name;
  std::string description;
};