#pragma once

#include "nlohmann/json.hpp"

enum class TradeSymbol {
  kPreciousStones,
  kQuartzSand,
  kSiliconCrystals,
  kAmmoniaIce,
  kLiquidHydrogen,
  kLiquidNitrogen,
  kIceWater,
  kExoticMatter,
  kAdvancedCircuitry,
  kGravitonEmitters,
  kIron,
  kIronOre,
  kCopper,
  kCopperOre,
  kAluminum,
  kAluminumOre,
  kSilver,
  kSilverOre,
  kGold,
  kGoldOre,
  kPlatinum,
  kPlatinumOre,
  kDiamonds,
  kUranite,
  kUraniteOre,
  kMeritium,
  kMeritiumOre,
  kHydrocarbon,
  kAntimatter,
  kFertilizers,
  kFabrics,
  kFood,
  kJewelry,
  kMachinery,
  kFirearms,
  kAssaultRifles,
  kMilitaryEquipment,
  kExplosives,
  kLabInstruments,
  kAmmunition,
  kElectronics,
  kShipPlating,
  kEquipment,
  kFuel,
  kMedicine,
  kDrugs,
  kClothing,
  kMicroprocessors,
  kPlastics,
  kPolynucleotides,
  kBiocomposites,
  kNanobots,
  kAiMainframes,
  kQuantumDrives,
  kRoboticDrones,
  kCyberImplants,
  kGeneTherapeutics,
  kNeuralChips,
  kMoodRegulators,
  kViralAgents,
  kMicroFusionGenerators,
  kSupergrains,
  kLaserRifles,
  kHolographics,
  kShipSalvage,
  kRelicTech,
  kNovelLifeforms,
  kBotanicalSpecimens,
  kCulturalArtifacts,
  kReactorSolarI,
  kReactorFusionI,
  kReactorFissionI,
  kReactorChemicalI,
  kReactorAntimatterI,
  kEngineImpulseDriveI,
  kEngineIonDriveI,
  kEngineIonDriveIi,
  kEngineHyperDriveI,
  kModuleMineralProcessorI,
  kModuleCargoHoldI,
  kModuleCrewQuartersI,
  kModuleEnvoyQuartersI,
  kModulePassengerCabinI,
  kModuleMicroRefineryI,
  kModuleOreRefineryI,
  kModuleFuelRefineryI,
  kModuleScienceLabI,
  kModuleJumpDriveI,
  kModuleJumpDriveIi,
  kModuleJumpDriveIii,
  kModuleWarpDriveI,
  kModuleWarpDriveIi,
  kModuleWarpDriveIii,
  kModuleShieldGeneratorI,
  kModuleShieldGeneratorIi,
  kMountGasSiphonI,
  kMountGasSiphonIi,
  kMountGasSiphonIii,
  kMountSurveyorI,
  kMountSurveyorIi,
  kMountSurveyorIii,
  kMountSensorArrayI,
  kMountSensorArrayIi,
  kMountSensorArrayIii,
  kMountMiningLaserI,
  kMountMiningLaserIi,
  kMountMiningLaserIii,
  kMountLaserCannonI,
  kMountMissileLauncherI,
  kMountTurretI,
};
NLOHMANN_JSON_SERIALIZE_ENUM(
    TradeSymbol,
    {
        {TradeSymbol::kPreciousStones, "PRECIOUS_STONES"},
        {TradeSymbol::kQuartzSand, "QUARTZ_SAND"},
        {TradeSymbol::kSiliconCrystals, "SILICON_CRYSTALS"},
        {TradeSymbol::kAmmoniaIce, "AMMONIA_ICE"},
        {TradeSymbol::kLiquidHydrogen, "LIQUID_HYDROGEN"},
        {TradeSymbol::kLiquidNitrogen, "LIQUID_NITROGEN"},
        {TradeSymbol::kIceWater, "ICE_WATER"},
        {TradeSymbol::kExoticMatter, "EXOTIC_MATTER"},
        {TradeSymbol::kAdvancedCircuitry, "ADVANCED_CIRCUITRY"},
        {TradeSymbol::kGravitonEmitters, "GRAVITON_EMITTERS"},
        {TradeSymbol::kIron, "IRON"},
        {TradeSymbol::kIronOre, "IRON_ORE"},
        {TradeSymbol::kCopper, "COPPER"},
        {TradeSymbol::kCopperOre, "COPPER_ORE"},
        {TradeSymbol::kAluminum, "ALUMINUM"},
        {TradeSymbol::kAluminumOre, "ALUMINUM_ORE"},
        {TradeSymbol::kSilver, "SILVER"},
        {TradeSymbol::kSilverOre, "SILVER_ORE"},
        {TradeSymbol::kGold, "GOLD"},
        {TradeSymbol::kGoldOre, "GOLD_ORE"},
        {TradeSymbol::kPlatinum, "PLATINUM"},
        {TradeSymbol::kPlatinumOre, "PLATINUM_ORE"},
        {TradeSymbol::kDiamonds, "DIAMONDS"},
        {TradeSymbol::kUranite, "URANITE"},
        {TradeSymbol::kUraniteOre, "URANITE_ORE"},
        {TradeSymbol::kMeritium, "MERITIUM"},
        {TradeSymbol::kMeritiumOre, "MERITIUM_ORE"},
        {TradeSymbol::kHydrocarbon, "HYDROCARBON"},
        {TradeSymbol::kAntimatter, "ANTIMATTER"},
        {TradeSymbol::kFertilizers, "FERTILIZERS"},
        {TradeSymbol::kFabrics, "FABRICS"},
        {TradeSymbol::kFood, "FOOD"},
        {TradeSymbol::kJewelry, "JEWELRY"},
        {TradeSymbol::kMachinery, "MACHINERY"},
        {TradeSymbol::kFirearms, "FIREARMS"},
        {TradeSymbol::kAssaultRifles, "ASSAULT_RIFLES"},
        {TradeSymbol::kMilitaryEquipment, "MILITARY_EQUIPMENT"},
        {TradeSymbol::kExplosives, "EXPLOSIVES"},
        {TradeSymbol::kLabInstruments, "LAB_INSTRUMENTS"},
        {TradeSymbol::kAmmunition, "AMMUNITION"},
        {TradeSymbol::kElectronics, "ELECTRONICS"},
        {TradeSymbol::kShipPlating, "SHIP_PLATING"},
        {TradeSymbol::kEquipment, "EQUIPMENT"},
        {TradeSymbol::kFuel, "FUEL"},
        {TradeSymbol::kMedicine, "MEDICINE"},
        {TradeSymbol::kDrugs, "DRUGS"},
        {TradeSymbol::kClothing, "CLOTHING"},
        {TradeSymbol::kMicroprocessors, "MICROPROCESSORS"},
        {TradeSymbol::kPlastics, "PLASTICS"},
        {TradeSymbol::kPolynucleotides, "POLYNUCLEOTIDES"},
        {TradeSymbol::kBiocomposites, "BIOCOMPOSITES"},
        {TradeSymbol::kNanobots, "NANOBOTS"},
        {TradeSymbol::kAiMainframes, "AI_MAINFRAMES"},
        {TradeSymbol::kQuantumDrives, "QUANTUM_DRIVES"},
        {TradeSymbol::kRoboticDrones, "ROBOTIC_DRONES"},
        {TradeSymbol::kCyberImplants, "CYBER_IMPLANTS"},
        {TradeSymbol::kGeneTherapeutics, "GENE_THERAPEUTICS"},
        {TradeSymbol::kNeuralChips, "NEURAL_CHIPS"},
        {TradeSymbol::kMoodRegulators, "MOOD_REGULATORS"},
        {TradeSymbol::kViralAgents, "VIRAL_AGENTS"},
        {TradeSymbol::kMicroFusionGenerators, "MICRO_FUSION_GENERATORS"},
        {TradeSymbol::kSupergrains, "SUPERGRAINS"},
        {TradeSymbol::kLaserRifles, "LASER_RIFLES"},
        {TradeSymbol::kHolographics, "HOLOGRAPHICS"},
        {TradeSymbol::kShipSalvage, "SHIP_SALVAGE"},
        {TradeSymbol::kRelicTech, "RELIC_TECH"},
        {TradeSymbol::kNovelLifeforms, "NOVEL_LIFEFORMS"},
        {TradeSymbol::kBotanicalSpecimens, "BOTANICAL_SPECIMENS"},
        {TradeSymbol::kCulturalArtifacts, "CULTURAL_ARTIFACTS"},
        {TradeSymbol::kReactorSolarI, "REACTOR_SOLAR_I"},
        {TradeSymbol::kReactorFusionI, "REACTOR_FUSION_I"},
        {TradeSymbol::kReactorFissionI, "REACTOR_FISSION_I"},
        {TradeSymbol::kReactorChemicalI, "REACTOR_CHEMICAL_I"},
        {TradeSymbol::kReactorAntimatterI, "REACTOR_ANTIMATTER_I"},
        {TradeSymbol::kEngineImpulseDriveI, "ENGINE_IMPULSE_DRIVE_I"},
        {TradeSymbol::kEngineIonDriveI, "ENGINE_ION_DRIVE_I"},
        {TradeSymbol::kEngineIonDriveIi, "ENGINE_ION_DRIVE_II"},
        {TradeSymbol::kEngineHyperDriveI, "ENGINE_HYPER_DRIVE_I"},
        {TradeSymbol::kModuleMineralProcessorI, "MODULE_MINERAL_PROCESSOR_I"},
        {TradeSymbol::kModuleCargoHoldI, "MODULE_CARGO_HOLD_I"},
        {TradeSymbol::kModuleCrewQuartersI, "MODULE_CREW_QUARTERS_I"},
        {TradeSymbol::kModuleEnvoyQuartersI, "MODULE_ENVOY_QUARTERS_I"},
        {TradeSymbol::kModulePassengerCabinI, "MODULE_PASSENGER_CABIN_I"},
        {TradeSymbol::kModuleMicroRefineryI, "MODULE_MICRO_REFINERY_I"},
        {TradeSymbol::kModuleOreRefineryI, "MODULE_ORE_REFINERY_I"},
        {TradeSymbol::kModuleFuelRefineryI, "MODULE_FUEL_REFINERY_I"},
        {TradeSymbol::kModuleScienceLabI, "MODULE_SCIENCE_LAB_I"},
        {TradeSymbol::kModuleJumpDriveI, "MODULE_JUMP_DRIVE_I"},
        {TradeSymbol::kModuleJumpDriveIi, "MODULE_JUMP_DRIVE_II"},
        {TradeSymbol::kModuleJumpDriveIii, "MODULE_JUMP_DRIVE_III"},
        {TradeSymbol::kModuleWarpDriveI, "MODULE_WARP_DRIVE_I"},
        {TradeSymbol::kModuleWarpDriveIi, "MODULE_WARP_DRIVE_II"},
        {TradeSymbol::kModuleWarpDriveIii, "MODULE_WARP_DRIVE_III"},
        {TradeSymbol::kModuleShieldGeneratorI, "MODULE_SHIELD_GENERATOR_I"},
        {TradeSymbol::kModuleShieldGeneratorIi, "MODULE_SHIELD_GENERATOR_II"},
        {TradeSymbol::kMountGasSiphonI, "MOUNT_GAS_SIPHON_I"},
        {TradeSymbol::kMountGasSiphonIi, "MOUNT_GAS_SIPHON_II"},
        {TradeSymbol::kMountGasSiphonIii, "MOUNT_GAS_SIPHON_III"},
        {TradeSymbol::kMountSurveyorI, "MOUNT_SURVEYOR_I"},
        {TradeSymbol::kMountSurveyorIi, "MOUNT_SURVEYOR_II"},
        {TradeSymbol::kMountSurveyorIii, "MOUNT_SURVEYOR_III"},
        {TradeSymbol::kMountSensorArrayI, "MOUNT_SENSOR_ARRAY_I"},
        {TradeSymbol::kMountSensorArrayIi, "MOUNT_SENSOR_ARRAY_II"},
        {TradeSymbol::kMountSensorArrayIii, "MOUNT_SENSOR_ARRAY_III"},
        {TradeSymbol::kMountMiningLaserI, "MOUNT_MINING_LASER_I"},
        {TradeSymbol::kMountMiningLaserIi, "MOUNT_MINING_LASER_II"},
        {TradeSymbol::kMountMiningLaserIii, "MOUNT_MINING_LASER_III"},
        {TradeSymbol::kMountLaserCannonI, "MOUNT_LASER_CANNON_I"},
        {TradeSymbol::kMountMissileLauncherI, "MOUNT_MISSILE_LAUNCHER_I"},
        {TradeSymbol::kMountTurretI, "MOUNT_TURRET_I"},
    })
