#pragma once

#include "nlohmann/json.hpp"

enum class WaypointTraitSymbol {
  kUncharted,
  kMarketplace,
  kShipyard,
  kOutpost,
  kScatteredSettlements,
  kSprawlingCities,
  kMegaStructures,
  kOvercrowded,
  kHighTech,
  kCorrupt,
  kBureaucratic,
  kTradingHub,
  kIndustrial,
  kBlackMarket,
  kResearchFacility,
  kMilitaryBase,
  kSurveillanceOutpost,
  kExplorationOutpost,
  kMineralDeposits,
  kCommonMetalDeposits,
  kPreciousMetalDeposits,
  kRareMetalDeposits,
  kMethanePools,
  kIceCrystals,
  kExplosiveGases,
  kStrongMagnetosphere,
  kVibrantAuroras,
  kSaltFlats,
  kCanyons,
  kPerpetualDaylight,
  kPerpetualOvercast,
  kDrySeabeds,
  kMagmaSeas,
  kSupervolcanoes,
  kAshClouds,
  kVastRuins,
  kMutatedFlora,
  kTerraformed,
  kExtremeTemperatures,
  kExtremePressure,
  kDiverseLife,
  kScarceLife,
  kFossils,
  kWeakGravity,
  kStrongGravity,
  kCrushingGravity,
  kToxicAtmosphere,
  kCorrosiveAtmosphere,
  kBreathableAtmosphere,
  kJovian,
  kRocky,
  kVolcanic,
  kFrozen,
  kSwamp,
  kBarren,
  kTemperate,
  kJungle,
  kOcean,
  kStripped,
};
NLOHMANN_JSON_SERIALIZE_ENUM(
    WaypointTraitSymbol,
    {
        {WaypointTraitSymbol::kUncharted, "UNCHARTED"},
        {WaypointTraitSymbol::kMarketplace, "MARKETPLACE"},
        {WaypointTraitSymbol::kShipyard, "SHIPYARD"},
        {WaypointTraitSymbol::kOutpost, "OUTPOST"},
        {WaypointTraitSymbol::kScatteredSettlements, "SCATTERED_SETTLEMENTS"},
        {WaypointTraitSymbol::kSprawlingCities, "SPRAWLING_CITIES"},
        {WaypointTraitSymbol::kMegaStructures, "MEGA_STRUCTURES"},
        {WaypointTraitSymbol::kOvercrowded, "OVERCROWDED"},
        {WaypointTraitSymbol::kHighTech, "HIGH_TECH"},
        {WaypointTraitSymbol::kCorrupt, "CORRUPT"},
        {WaypointTraitSymbol::kBureaucratic, "BUREAUCRATIC"},
        {WaypointTraitSymbol::kTradingHub, "TRADING_HUB"},
        {WaypointTraitSymbol::kIndustrial, "INDUSTRIAL"},
        {WaypointTraitSymbol::kBlackMarket, "BLACK_MARKET"},
        {WaypointTraitSymbol::kResearchFacility, "RESEARCH_FACILITY"},
        {WaypointTraitSymbol::kMilitaryBase, "MILITARY_BASE"},
        {WaypointTraitSymbol::kSurveillanceOutpost, "SURVEILLANCE_OUTPOST"},
        {WaypointTraitSymbol::kExplorationOutpost, "EXPLORATION_OUTPOST"},
        {WaypointTraitSymbol::kMineralDeposits, "MINERAL_DEPOSITS"},
        {WaypointTraitSymbol::kCommonMetalDeposits, "COMMON_METAL_DEPOSITS"},
        {WaypointTraitSymbol::kPreciousMetalDeposits,
         "PRECIOUS_METAL_DEPOSITS"},
        {WaypointTraitSymbol::kRareMetalDeposits, "RARE_METAL_DEPOSITS"},
        {WaypointTraitSymbol::kMethanePools, "METHANE_POOLS"},
        {WaypointTraitSymbol::kIceCrystals, "ICE_CRYSTALS"},
        {WaypointTraitSymbol::kExplosiveGases, "EXPLOSIVE_GASES"},
        {WaypointTraitSymbol::kStrongMagnetosphere, "STRONG_MAGNETOSPHERE"},
        {WaypointTraitSymbol::kVibrantAuroras, "VIBRANT_AURORAS"},
        {WaypointTraitSymbol::kSaltFlats, "SALT_FLATS"},
        {WaypointTraitSymbol::kCanyons, "CANYONS"},
        {WaypointTraitSymbol::kPerpetualDaylight, "PERPETUAL_DAYLIGHT"},
        {WaypointTraitSymbol::kPerpetualOvercast, "PERPETUAL_OVERCAST"},
        {WaypointTraitSymbol::kDrySeabeds, "DRY_SEABEDS"},
        {WaypointTraitSymbol::kMagmaSeas, "MAGMA_SEAS"},
        {WaypointTraitSymbol::kSupervolcanoes, "SUPERVOLCANOES"},
        {WaypointTraitSymbol::kAshClouds, "ASH_CLOUDS"},
        {WaypointTraitSymbol::kVastRuins, "VAST_RUINS"},
        {WaypointTraitSymbol::kMutatedFlora, "MUTATED_FLORA"},
        {WaypointTraitSymbol::kTerraformed, "TERRAFORMED"},
        {WaypointTraitSymbol::kExtremeTemperatures, "EXTREME_TEMPERATURES"},
        {WaypointTraitSymbol::kExtremePressure, "EXTREME_PRESSURE"},
        {WaypointTraitSymbol::kDiverseLife, "DIVERSE_LIFE"},
        {WaypointTraitSymbol::kScarceLife, "SCARCE_LIFE"},
        {WaypointTraitSymbol::kFossils, "FOSSILS"},
        {WaypointTraitSymbol::kWeakGravity, "WEAK_GRAVITY"},
        {WaypointTraitSymbol::kStrongGravity, "STRONG_GRAVITY"},
        {WaypointTraitSymbol::kCrushingGravity, "CRUSHING_GRAVITY"},
        {WaypointTraitSymbol::kToxicAtmosphere, "TOXIC_ATMOSPHERE"},
        {WaypointTraitSymbol::kCorrosiveAtmosphere, "CORROSIVE_ATMOSPHERE"},
        {WaypointTraitSymbol::kBreathableAtmosphere, "BREATHABLE_ATMOSPHERE"},
        {WaypointTraitSymbol::kJovian, "JOVIAN"},
        {WaypointTraitSymbol::kRocky, "ROCKY"},
        {WaypointTraitSymbol::kVolcanic, "VOLCANIC"},
        {WaypointTraitSymbol::kFrozen, "FROZEN"},
        {WaypointTraitSymbol::kSwamp, "SWAMP"},
        {WaypointTraitSymbol::kBarren, "BARREN"},
        {WaypointTraitSymbol::kTemperate, "TEMPERATE"},
        {WaypointTraitSymbol::kJungle, "JUNGLE"},
        {WaypointTraitSymbol::kOcean, "OCEAN"},
        {WaypointTraitSymbol::kStripped, "STRIPPED"},
    })

struct WaypointTrait {
 public:
  NLOHMANN_DEFINE_TYPE_INTRUSIVE(WaypointTrait, symbol, name, description)

 public:
  bool operator==(const WaypointTrait&) const = default;

 public:
  WaypointTraitSymbol symbol{};
  std::string name;
  std::string description;
};